version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: integrate-it-bot:tag
    environment:
      - LOGGING_LEVEL=WARNING
    env_file:
      - secrets.env
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: integrate-it-web:tag
    environment:
      - LOGGING_LEVEL=WARNING
    env_file:
      - secrets.env
    ports:
      - "80:65010"